### PR TITLE
Upgrade aeson, hint, network

### PR DESCRIPTION
**Pull request by bergmark**

### CODE REVIEW

**Comment by tathougies** [comment]
Is this for stackage

**Comment by bergmark** [comment]
Yep!

**Comment by tathougies** [comment]
Thank you! Do I need to push the changes to hackage to make stackage pick them up?

**Comment by mitchellwrosen** [comment]
@tathougies Yep, or you could make a hackage revision (which reduces cabal new-build cache thrashing). There's a tool called `hackage-cli` that works as follows:

```haskell
-- in ~/.netrc
machine hackage.haskell.org login <username> password <password>

-- in shell
hackage-cli push-cabal --incr-rev --publish
```

You can get it here: https://github.com/hackage-trustees/hackage-cli

**Pull request merged**
