### PR TITLE
Use Sql[Insert,Update,Delete] for MonadBeam[Insert,Update,Delete]Returning

### PR DESCRIPTION
**Pull request by kmicklas**
This improves composability and consistency with `runSelectReturningList`.

### CODE REVIEW

**Comment by tathougies** [comment]
Okay, yeah. I like this! Thank you!

**Comment by kmicklas** [comment]
@tathougies It looks like this got force pushed out of `travis/beam-0.8.0.0`. Was there an issue with the PR?

**Comment by tathougies** [comment]
I don't think I've force pushed anything to the repo in the past week. When I pull locally and run `git log`, I see the commit:

```
commit 81e8bdf63fdbdee3d1241dcbc8e586f99a88e9fa
Author: Ken Micklas <kmicklas@gmail.com>
Date:   Sat Jan 19 08:49:15 2019 -0500

    Use Sql[Insert,Update,Delete] for MonadBeam[Insert,Update,Delete]Returning

```

It also seems like the patch has been applied, when I look at `BeamExtensions,hs`. Could it be some git weirdness?

**Comment by kmicklas** [comment]
I don't see it on here: https://github.com/tathougies/beam/commits/travis/beam-0.8.0.0

**Comment by tathougies** [comment]
So I couldn't find your commit on my work computer either, but I got home and pushed from my usual development laptop (the one whose log output I posted this morning), and it looks to be there now. Not sure how that happened, since I merged the branch using the web interface.

**Pull request merged**
