### PR TITLE
More exports in beam-migrate

### PR DESCRIPTION
**Pull request by 3noch**

### CODE REVIEW

**Comment by 3noch** [comment]
@tathougies I also can't seem to figure how to actually use `executeMigration` since it takes a `Migration` and not `MigrationSteps`. The example in the repo only takes me as far as `MigrationSteps` but after that I'm at a loss.

**Comment by tathougies** [comment]
@3noch the `migrationStepsToMigration` function can be used to unfold a `MigrationSteps`

Something like

`migrationStepsToMigration (\stepNm -> executeMigration runNoReturn) <migrationsteps>`

**Comment by 3noch** [comment]
@tathougies Thanks.

**Comment by 3noch** [comment]
Anything I can do more to make this merge-worthy?

**Comment by tathougies** [comment]
No it looks good. If there are no more questions, I'll merge it.

**Comment by 3noch** [comment]
No I'm good with these changes.

**Pull request merged**
