### PR TITLE
Get db migration backend with schemas

### PR DESCRIPTION
**Pull request by phadej**
Builds on top of #445

### CODE REVIEW

**Comment by phadej** [comment]
ping

**Comment by phadej** [comment]
This PR contained commit from #445, you could just merged this :(

**Comment by phadej** [comment]
Rebased.

**Comment by kmicklas** [comment]
> This PR contained commit from #445, you could just merged this :(

Sorry, I didn't see this one until I had already merged #445. :smile:

**Comment by phadej** [comment]
May I ask what the point of rebasing if you anyway rewrite structure (by rebase and merge GitHub button?)

**Comment by kmicklas** [comment]
I wasn't sure if GitHub would properly skip the first commit. I generally prefer simply merging which avoids these issues but I think @tathougies prefers having a clean linear history.

**Pull request merged**
